### ISSUE TITLE
Current mallob solution output format different from format expected by bridge 

### ISSUE THREAD

**Issue by ignaloidas** [domschrei/mallob-ipasir-bridge#3]
Current mallob versions output an array of  DIMACS format lines, while this bridge expects an array of integers corresponding to literals, because of which the current version of this bridge fails with current version of mallob.

**Comment by domschrei** [comment]
Indeed, thanks for letting me know. I'll prepare a fix ASAP.

**Comment by domschrei** [comment]
Sorry for taking this long. 

The default way to transfer models back to the bridge from Mallob is actually via a pipe of raw data. This can be enabled with the Mallob option `-ps=2` ("pipe solutions = all"). (You must then take care to really read out every model with the bridge, otherwise Mallob will begin to hang at some point.)

Did you already try this? In most cases this should be preferable to bundling the model in the JSON since it's more efficient this way.

That being said, I'll also update the bridge code to properly react to the vector of DIMACS solution strings.

**Comment by domschrei** [comment]
I've patched in the updated handling of models (and failed assumptions) coming from within the response JSON. Just let me know if one of these solutions works for you.

**Comment by ignaloidas** [comment]
Hey, sorry, took a while to be able to get back to this.

`-ps=2` somehow didn't work for me, every solution reads 0 bytes for some reason, not sure why. But now it works just fine even without it, so thanks!
